### ISSUE TITLE
SR-18-0000138 FD new record type Kitchen Hood Cleaning License 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#35] opened 2018-06-28 21:06 UTC
FD new record type Kitchen Hood Cleaning License - See attached document for original request. As part of the Fire Fee SR, they have a new record type. 
This will be a clone of Fire Extinguisher License but they want less fields required. The fee will be $125. It also needs to work with the existing clerks licensing renewal process. 
 - [ ] Going to set this to Review in Process until specifications can be done
06/28/2018 itjag -  Attached updated emails from Bill.

**Comment by RikiSjachrani-COM** [comment] 2018-06-29 14:41
@JaneSchneider-COM this one is pretty much done, and is in Ready to Test. I think there are some minor tweaks from the first round of testing but other than that it's done. I'll add to the SR what remaining changes and we can send it back to Bill

**Comment by JaneSchneider-COM** [comment] 2018-06-29 14:46
Oh, OK, then I will start on SR-18-0162 instead. If you want me to make any changes to this one (138), just let me know.

**Comment by JaneSchneider-COM** [comment] 2018-07-09 14:42
@RikiSjachrani-COM : I have completed the auto-numbering of the License Number field in Dev & Test. If this SR needs any additional changes, please let me know.

**Comment by JacquelineGoltz-COM** [comment] 2018-07-09 19:37
@JaneSchneider-COM I completed records in Dev and Test.  Both created the auto numbered license numbers correctly.

**Comment by RikiSjachrani-COM** [comment] 2018-07-09 19:41
Please notify Bill and update the SR accordingly

**Comment by JaneSchneider-COM** [comment] 2018-07-27 14:41
Two questions: 

1. For converting the existing FireExtinguisherMaint Alt-IDs for to the new format, I need some direction regarding what to do with Alt-IDs that:
-  Don't have a Certification/License number
-  Have legacy Alt-IDs, e.g. 51194-41321

Also, are we converting all existing records, regardless of current status? Example, Closed, Inactive, Void, etc?
I did do a conversion in Dev of all records, except the Voided ones, but I had to create some arbitrarily assigned Alt-IDs, so I do not want to proceed to Test until I know what the rules are? If you want me to email Bill to get this info, please let me know, and I will send these questions.

2. Does Bill still want an email to be sent out at license issuance now that it was decided that the license will still be mailed out and not attached to the email?

**Comment by RikiSjachrani-COM** [comment] 2018-08-08 19:34
We met with Bill at the bi-weekly fire meeting and reminded him of @JaneSchneider-COM email on what to do, I'm going to attached that email to the SR and set it to Additional Information Required. Maybe we should follow up with him by the end of next week if we don't hear back

**Comment by JaneSchneider-COM** [comment] 2018-08-20 21:16
Did analysis of the 250 existing production FireExtinguisherMaint records based on Bill's response to my first email about which records to convert:

-  	We will not be updating any records that are Inactive, Void or Closed.  We should convert any Expired records that have been expired less than 1 year.  All older Expired records do not need to be converted
- 	I am hoping this addresses the rest of the conditions since we aren’t converting the older ones.  If not let me know.

Per the above rules, I determined that 
- 86 records should be converted
- 156 should not be converted
- Not sure about 8 records; asking Bill to advise

Sent follow-up email to Bill with this spreadsheet attached. Mostly need to know if my proposed idea to convert all-numeric legacy records is acceptable. 
[FireExtinguisherMaint_RecordNbr_Conversion.xlsx](https://github.com/City-of-Madison/Development-Team-2/files/2303970/FireExtinguisherMaint_RecordNbr_Conversion.xlsx)

**Comment by JaneSchneider-COM** [comment] 2018-08-21 15:04
Bill responded as follows to my questions about the Alt-ID conversion:
•	Yes, Only convert FIREML-2018-00072
•	Legacy records, Yes convert as proposed 
•	Legacy Record with cert # in business name, please convert as proposed
•	FIREML-2011-00035  His number is A766.  I have updated this in Accela.

I know have enough info to do the conversion SQL scripts.

**Comment by JaneSchneider-COM** [comment] 2018-08-23 13:53
@JacquelineGoltz-COM: Is there supposed to be a fee item specific to Kitchen Hood Cleaning? Currently, the fee being assessed is "Fire Ext Maint Contractor Application Fee". I looked in the FIRLICENSE fee schedule, and there is no fee item specific to Kitchen Hood Cleaning...is this by design? Or do we need to create one?

**Comment by JacquelineGoltz-COM** [comment] 2018-08-23 14:49
@JaneSchneider-COM  Thanks for catching that.  The fee is to $125 according to my notes.  The Fee Code of LICENSE could have the description changed to include both.  I feel we should create a new fee code though for Kitchenhood.  What are your thoughts?

**Comment by JacquelineGoltz-COM** [comment] 2018-08-23 14:50
Jerry and Ann replied with the updated email language.  See below:

Hello,
Your license (FIRHCL-2018-H000001) has been issued and will be mailed to you.  
                             This number (H000001) shall be used on all documentation related to the inspection you are performing.  For instance:
•	If a Hood Cleaning License – your number must be on the decal left on the hood when the cleaning is complete
•	If a Fire Extinguisher Maintenance License – your number must be on the tag placed on each extinguisher when the maintenance is completed
        If you have any questions about the use or renewal of your license, please contact us using the information below.
Thank you,

City of Madison Fire Department
Phone: (608) 266-4420 
Email: fireprevention@cityofmadison.com

**Comment by JaneSchneider-COM** [comment] 2018-08-23 14:56
@JacquelineGoltz-COM : Yes, I think a separate fee code for the Kitchen Hood Cleaning should be created.
Maybe call it, "Fire Kitch Hood Clean Contractor Application Fee"?

**Comment by JacquelineGoltz-COM** [comment] 2018-08-23 18:49
The license are ready for testing.  I will send email to Bill and his staff.

**Comment by JaneSchneider-COM** [comment] 2018-08-30 16:27
@JacquelineGoltz-COM: I looked at the batch script for the Fire Renewals (BATCH_RENEWAL_FIRE) , and it requires an entry for the given record type and associated fee schedule in Standard Choice BATCH:FeeScheduleLookup.
This line has been entered in Dev & Test for Licenses/Fire/KitchenHoodCleaning/NA.
FYI - The Batch Job = Renewal2012Fire
So, other than moving to Prod, the KitchenHoodCleaning license is all set for renewals next year when the batch job runs. 
Also FYI - FireExtinguisherMaint Licenses are already referenced in BATCH:FeeScheduleLookup in all three environments.

**Comment by JacquelineGoltz-COM** [comment] 2018-09-13 18:33
I have sent a follow up email to Bill and the fire staff.  I reminded them that this SR is in test.  I am not moving this to production yet due to the flooding issues that may have set them behind.

**Comment by JacquelineGoltz-COM** [comment] 2018-09-26 18:00
Plan is to move to production Monday October 1.  Talked to Bill and will verify with Ann Blackdeer.

**Comment by JaneSchneider-COM** [comment] 2018-09-26 18:06
I am out all next week, so won't be around to facilitate the move to production. 
Do you want me to go over the deployment check list with you or someone this week? Probably would be a good idea.

**Comment by JacquelineGoltz-COM** [comment] 2018-09-26 18:31
Yes we can go over it tomorrow or Friday morning.

**Closed** 2018-10-04 18:42 UTC
Labels: Epic
